-- Banking Database Schema (PostgreSQL)
-- Supports: accounts, loans with payment schedules, transactions, error logging

-- Drop existing objects in correct dependency order
DROP PROCEDURE IF EXISTS make_payment(INT, INT, NUMERIC, TEXT, VARCHAR);
DROP PROCEDURE IF EXISTS generate_payment_schedule(INT);
DROP TABLE IF EXISTS error_logs;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS loan_payment_schedule;
DROP TABLE IF EXISTS loans;
DROP TABLE IF EXISTS bank_accounts;

-- -------------------------------------------------------------------------
-- Table: bank_accounts
-- Stores individual bank accounts (members, trainers, clubs)
-- -------------------------------------------------------------------------
CREATE TABLE bank_accounts (
    account_id      SERIAL PRIMARY KEY,
    account_number  VARCHAR(20)  UNIQUE NOT NULL,
    account_holder  VARCHAR(100) NOT NULL,
    account_type    VARCHAR(20)  NOT NULL DEFAULT 'checking',  -- checking | savings | club
    balance         NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    fitness_ref_type VARCHAR(20),   -- 'member' | 'trainer' | 'club'
    fitness_ref_id  INT,            -- ID in the fitness database
    created_at      TIMESTAMPTZ  DEFAULT NOW()
);

-- -------------------------------------------------------------------------
-- Table: loans
-- Stores credit/loan records linked to a bank account
-- -------------------------------------------------------------------------
CREATE TABLE loans (
    loan_id         SERIAL PRIMARY KEY,
    account_id      INT          NOT NULL REFERENCES bank_accounts(account_id) ON DELETE CASCADE,
    principal       NUMERIC(15, 2) NOT NULL CHECK (principal > 0),
    annual_rate     NUMERIC(6, 3) NOT NULL CHECK (annual_rate > 0),   -- e.g. 12.500 %
    term_months     INT          NOT NULL CHECK (term_months > 0),
    start_date      DATE         NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'active'  -- active | paid | defaulted
                    CHECK (status IN ('active', 'paid', 'defaulted')),
    created_at      TIMESTAMPTZ  DEFAULT NOW()
);

-- -------------------------------------------------------------------------
-- Table: loan_payment_schedule
-- Amortisation schedule generated by generate_payment_schedule()
-- -------------------------------------------------------------------------
CREATE TABLE loan_payment_schedule (
    schedule_id       SERIAL PRIMARY KEY,
    loan_id           INT          NOT NULL REFERENCES loans(loan_id) ON DELETE CASCADE,
    payment_number    INT          NOT NULL,
    due_date          DATE         NOT NULL,
    principal_amount  NUMERIC(15, 2) NOT NULL,
    interest_amount   NUMERIC(15, 2) NOT NULL,
    total_payment     NUMERIC(15, 2) NOT NULL,
    paid              BOOLEAN      NOT NULL DEFAULT FALSE,
    paid_at           TIMESTAMPTZ,
    UNIQUE (loan_id, payment_number)
);

-- -------------------------------------------------------------------------
-- Table: transactions
-- Accumulates every executed payment
-- -------------------------------------------------------------------------
CREATE TABLE transactions (
    transaction_id  SERIAL PRIMARY KEY,
    debit_account_id  INT          NOT NULL REFERENCES bank_accounts(account_id),
    credit_account_id INT          NOT NULL REFERENCES bank_accounts(account_id),
    amount          NUMERIC(15, 2) NOT NULL CHECK (amount > 0),
    description     TEXT,
    reference       VARCHAR(100),   -- external reference, e.g. "fitness:membership:3"
    executed_at     TIMESTAMPTZ  DEFAULT NOW()
);

-- -------------------------------------------------------------------------
-- Table: error_logs
-- Records failed payment attempts without interrupting the caller
-- -------------------------------------------------------------------------
CREATE TABLE error_logs (
    log_id          SERIAL PRIMARY KEY,
    operation       VARCHAR(50)  NOT NULL,
    error_message   TEXT         NOT NULL,
    details         JSONB,
    logged_at       TIMESTAMPTZ  DEFAULT NOW()
);

-- =========================================================================
-- Procedure: generate_payment_schedule
-- Calculates an annuity payment schedule for the given loan and inserts
-- rows into loan_payment_schedule.
-- Deletes any previously generated schedule for the same loan first.
-- =========================================================================
CREATE OR REPLACE PROCEDURE generate_payment_schedule(p_loan_id INT)
LANGUAGE plpgsql
AS $$
DECLARE
    v_principal    NUMERIC(15, 2);
    v_annual_rate  NUMERIC(6, 3);
    v_term_months  INT;
    v_start_date   DATE;
    v_monthly_rate NUMERIC(20, 10);
    v_payment      NUMERIC(15, 2);
    v_balance      NUMERIC(15, 2);
    v_interest     NUMERIC(15, 2);
    v_principal_part NUMERIC(15, 2);
    i              INT;
BEGIN
    -- Load loan details
    SELECT principal, annual_rate, term_months, start_date
    INTO   v_principal, v_annual_rate, v_term_months, v_start_date
    FROM   loans
    WHERE  loan_id = p_loan_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Loan % not found', p_loan_id;
    END IF;

    -- Remove any existing schedule
    DELETE FROM loan_payment_schedule WHERE loan_id = p_loan_id;

    v_monthly_rate := v_annual_rate / 100.0 / 12.0;
    v_balance      := v_principal;

    -- Annuity payment: M = P * r * (1+r)^n / ((1+r)^n - 1)
    IF v_monthly_rate = 0 THEN
        v_payment := ROUND(v_principal / v_term_months, 2);
    ELSE
        v_payment := ROUND(
            v_principal
            * v_monthly_rate
            * POWER(1 + v_monthly_rate, v_term_months)
            / (POWER(1 + v_monthly_rate, v_term_months) - 1),
            2
        );
    END IF;

    FOR i IN 1 .. v_term_months LOOP
        v_interest      := ROUND(v_balance * v_monthly_rate, 2);
        v_principal_part := v_payment - v_interest;

        -- Last payment: adjust for rounding drift
        IF i = v_term_months THEN
            v_principal_part := v_balance;
            v_payment        := v_principal_part + v_interest;
        END IF;

        INSERT INTO loan_payment_schedule
            (loan_id, payment_number, due_date,
             principal_amount, interest_amount, total_payment)
        VALUES
            (p_loan_id, i,
             v_start_date + (i * INTERVAL '1 month'),
             v_principal_part, v_interest, v_payment);

        v_balance := v_balance - v_principal_part;
    END LOOP;
END;
$$;

-- =========================================================================
-- Procedure: make_payment
-- Transfers p_amount from one account to another.
-- Validates input, updates balances, inserts a transaction record.
-- On ANY error the payment is NOT executed; the error is logged instead.
-- =========================================================================
CREATE OR REPLACE PROCEDURE make_payment(
    p_debit_account_id  INT,
    p_credit_account_id INT,
    p_amount            NUMERIC,
    p_description       TEXT    DEFAULT NULL,
    p_reference         VARCHAR DEFAULT NULL
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_debit_balance  NUMERIC(15, 2);
    v_credit_exists  BOOLEAN;
    v_err_details    JSONB;
BEGIN
    -- Validation 1: amount must be positive
    IF p_amount IS NULL OR p_amount <= 0 THEN
        INSERT INTO error_logs (operation, error_message, details)
        VALUES ('make_payment', 'Amount must be positive',
                jsonb_build_object(
                    'debit_account_id',  p_debit_account_id,
                    'credit_account_id', p_credit_account_id,
                    'amount',            p_amount,
                    'reference',         p_reference
                ));
        RETURN;
    END IF;

    -- Validation 2: debit and credit accounts must differ
    IF p_debit_account_id = p_credit_account_id THEN
        INSERT INTO error_logs (operation, error_message, details)
        VALUES ('make_payment', 'Debit and credit accounts must be different',
                jsonb_build_object(
                    'account_id', p_debit_account_id,
                    'amount',     p_amount,
                    'reference',  p_reference
                ));
        RETURN;
    END IF;

    -- Validation 3: debit account must exist and have sufficient funds
    SELECT balance INTO v_debit_balance
    FROM   bank_accounts
    WHERE  account_id = p_debit_account_id
    FOR UPDATE;

    IF NOT FOUND THEN
        INSERT INTO error_logs (operation, error_message, details)
        VALUES ('make_payment', 'Debit account not found',
                jsonb_build_object(
                    'debit_account_id', p_debit_account_id,
                    'reference',        p_reference
                ));
        RETURN;
    END IF;

    IF v_debit_balance < p_amount THEN
        INSERT INTO error_logs (operation, error_message, details)
        VALUES ('make_payment', 'Insufficient funds',
                jsonb_build_object(
                    'debit_account_id', p_debit_account_id,
                    'balance',          v_debit_balance,
                    'amount',           p_amount,
                    'reference',        p_reference
                ));
        RETURN;
    END IF;

    -- Validation 4: credit account must exist (lock it for update)
    SELECT EXISTS (
        SELECT 1 FROM bank_accounts
        WHERE  account_id = p_credit_account_id
        FOR UPDATE
    ) INTO v_credit_exists;

    IF NOT v_credit_exists THEN
        INSERT INTO error_logs (operation, error_message, details)
        VALUES ('make_payment', 'Credit account not found',
                jsonb_build_object(
                    'credit_account_id', p_credit_account_id,
                    'reference',         p_reference
                ));
        RETURN;
    END IF;

    -- Execute the payment
    UPDATE bank_accounts SET balance = balance - p_amount WHERE account_id = p_debit_account_id;
    UPDATE bank_accounts SET balance = balance + p_amount WHERE account_id = p_credit_account_id;

    INSERT INTO transactions
        (debit_account_id, credit_account_id, amount, description, reference)
    VALUES
        (p_debit_account_id, p_credit_account_id, p_amount, p_description, p_reference);

EXCEPTION WHEN OTHERS THEN
    -- Catch unexpected errors: log them, do not re-raise
    INSERT INTO error_logs (operation, error_message, details)
    VALUES ('make_payment', SQLERRM,
            jsonb_build_object(
                'debit_account_id',  p_debit_account_id,
                'credit_account_id', p_credit_account_id,
                'amount',            p_amount,
                'reference',         p_reference,
                'sqlstate',          SQLSTATE
            ));
END;
$$;

-- =========================================================================
-- Sample data
-- =========================================================================

-- Bank accounts for clubs
INSERT INTO bank_accounts (account_number, account_holder, account_type, balance, fitness_ref_type, fitness_ref_id) VALUES
('BANK-CLUB-001', 'FitLife Downtown',  'club', 50000.00, 'club', 1),
('BANK-CLUB-002', 'FitLife Uptown',    'club', 45000.00, 'club', 2),
('BANK-CLUB-003', 'FitLife Brooklyn',  'club', 55000.00, 'club', 3);

-- Bank accounts for members
INSERT INTO bank_accounts (account_number, account_holder, account_type, balance, fitness_ref_type, fitness_ref_id) VALUES
('BANK-MBR-001', 'John Doe',       'checking', 5000.00, 'member', 1),
('BANK-MBR-002', 'Sarah Smith',    'checking', 3500.00, 'member', 2),
('BANK-MBR-003', 'Michael Johnson','checking', 8000.00, 'member', 3),
('BANK-MBR-004', 'Emily Brown',    'checking', 4200.00, 'member', 4),
('BANK-MBR-005', 'David Wilson',   'checking', 2000.00, 'member', 5);

-- Bank accounts for trainers
INSERT INTO bank_accounts (account_number, account_holder, account_type, balance, fitness_ref_type, fitness_ref_id) VALUES
('BANK-TRN-001', 'Alex Martinez',  'savings', 12000.00, 'trainer', 1),
('BANK-TRN-002', 'Jessica Lee',    'savings', 11000.00, 'trainer', 2),
('BANK-TRN-003', 'Robert Taylor',  'savings', 13000.00, 'trainer', 3),
('BANK-TRN-004', 'Maria Garcia',   'savings', 10500.00, 'trainer', 4);

-- Sample loan: Michael Johnson took a 12-month loan to cover VIP membership
INSERT INTO loans (account_id, principal, annual_rate, term_months, start_date) VALUES
(7, 1499.99, 15.0, 12, '2024-01-20');

-- Generate payment schedule for loan 1
CALL generate_payment_schedule(1);
